# Generated by Django 5.2.4 on 2025-07-31 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_num', models.IntegerField(max_length=10)),
                ('student_firstname', models.CharField(max_length=100)),
                ('student_lastname', models.CharField(max_length=100)),
                ('student_email', models.EmailField(max_length=100)),
                ('student_course', models.CharField(max_length=100)),
            ],
        ),
    ]
